# Generated by Django 3.1 on 2020-08-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='type',
            field=models.IntegerField(),
        ),
    ]
