# Generated by Django 3.1 on 2020-08-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstatus',
            old_name='description',
            new_name='s_description',
        ),
    ]
