# Generated by Django 3.1 on 2020-08-21 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_auto_20200821_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverstatus',
            old_name='s_description',
            new_name='description',
        ),
    ]
