# Generated by Django 3.1 on 2020-08-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0002_auto_20200811_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time',
            field=models.IntegerField(auto_created=True),
        ),
    ]
