# Generated by Django 3.1 on 2020-08-16 02:49

from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0003_auto_20200811_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time',
            field=models.IntegerField(auto_created=True, default=time.time),
        ),
    ]
