# Generated by Django 3.1 on 2020-08-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0004_auto_20200816_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time',
            field=models.DateTimeField(auto_created=True),
        ),
    ]
