# Generated by Django 3.1 on 2020-08-16 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0005_auto_20200816_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now),
        ),
    ]
