# Generated by Django 3.1 on 2020-08-16 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0006_auto_20200816_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='time',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
